#!/usr/bin/env bash
# SPDX-License-Identifier: Unlicense
#
# update-shipped-locales.sh
#
# Rewrites app/policy/locales.txt from Weblate's per-language statistics
# (09 Shipped locales and per-app language): `en-US` (the base) plus every
# language at least 90 % translated across all string components when the
# minor release is prepared (PO-14). Runs during the minor-release checklist;
# `check-apk.sh`/`check-desktop-image.sh` compare the packaged locales with
# this file.
#
# Configuration: WEBLATE_API (default Hosted Weblate), WEBLATE_PROJECT
# (default neutrodyne), WEBLATE_TOKEN for a private project. The statistics
# endpoint and field names are Unverified (09 open questions) — the script
# reads the documented `data[].translated_percent`-style fields and fails
# loudly rather than writing a wrong list.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." >/dev/null 2>&1 && pwd -P)"
OUT="$REPO_ROOT/app/policy/locales.txt"

WEBLATE_API="${WEBLATE_API:-https://hosted.weblate.org/api}"
WEBLATE_PROJECT="${WEBLATE_PROJECT:-neutrodyne}"
THRESHOLD=90 # PO-14: a language ships when every string component is >= 90 % translated

command -v curl >/dev/null 2>&1 || { echo "update-shipped-locales: curl not found" >&2; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo "update-shipped-locales: python3 not found" >&2; exit 2; }

AUTH=()
[ -n "${WEBLATE_TOKEN:-}" ] && AUTH=(-H "Authorization: Token $WEBLATE_TOKEN")

# Per-language translation statistics for the whole project (all components).
curl -fsSL "${AUTH[@]}" "$WEBLATE_API/projects/$WEBLATE_PROJECT/languages/" -o "$REPO_ROOT/.locales-stats.json"
trap 'rm -f "$REPO_ROOT/.locales-stats.json"' EXIT

python3 - "$REPO_ROOT/.locales-stats.json" "$OUT" "$THRESHOLD" <<'PYEOF'
import json, sys

stats_path, out, threshold = sys.argv[1], sys.argv[2], int(sys.argv[3])
data = json.load(open(stats_path, encoding="utf-8"))
# Hosted Weblate answers { "results": [ { "code": "de", "translated_percent": 97.3,
# "total_percent": ... } ], ... } — take the strictest percentage field present.
rows = data.get("results", data if isinstance(data, list) else [])
shipped = []
for row in rows:
    code = row.get("code") or row.get("language")
    pct = row.get("translated_percent", row.get("translated_words_percent"))
    if code is None or pct is None:
        sys.exit("update-shipped-locales: unexpected statistics shape "
                 f"(keys {sorted(row)}); 09 open question, read the Weblate API docs")
    if code in ("en", "en_US", "en-US"):
        continue  # the base locale always ships
    if pct >= threshold:
        shipped.append(code.replace("_", "-"))

lines = [
    "# SPDX-License-Identifier: Unlicense",
    "# Shipped locales, regenerated by scripts/l10n/update-shipped-locales.sh",
    "# during the minor-release checklist (09): en-US plus every language",
    f"# >= {threshold} % translated across all string components (PO-14).",
    "en-US",
] + sorted(shipped)
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"update-shipped-locales: {out} now lists en-US + {len(shipped)} locale(s): {sorted(shipped)}")
PYEOF
