// SPDX-License-Identifier: Unlicense
package ch.lkmc.neutrodyne.desktop.platform

import ch.lkmc.neutrodyne.core.model.InstallKind

/**
 * The packaging-pipeline facts `DatabaseOpener` needs before 11's full `BuildInfo` object lands
 * (M0b): `install-kind` is a one-line classpath resource the image copies carry; its absence —
 * `gradle run`, tests — means [InstallKind.DEV] (11 Release layout).
 */
internal object DesktopBuildInfo {
    private const val INSTALL_KIND_RESOURCE = "install-kind"
    private const val BUILD_INFO_RESOURCE = "build-info.properties"

    val installKind: InstallKind by lazy {
        val wire =
            DesktopBuildInfo::class.java.classLoader
                .getResource(INSTALL_KIND_RESOURCE)
                ?.readText()
                ?.trim()
        InstallKind.entries.firstOrNull { it.wire == wire } ?: InstallKind.DEV
    }

    /**
     * `build-info.properties`, generated by `:desktopApp`'s `writeBuildInfoProperties` task from
     * the gradle.properties single source — the interim counterpart of `:app`'s BuildConfig fields
     * until M0b's packaging pipeline stamps the release facts (11). A missing resource (tests)
     * reads as empty values.
     */
    private val props: java.util.Properties by lazy {
        java.util.Properties().apply {
            DesktopBuildInfo::class.java.classLoader
                .getResourceAsStream(BUILD_INFO_RESOURCE)
                ?.use { load(it) }
        }
    }

    /** Dev builds report `0.1.0-dev`; the packaging pipeline stamps the tag version (M0b). */
    val versionName: String get() = props.getProperty("versionName", "0.1.0-dev")

    val repoUrl: String get() = props.getProperty("repoUrl", "")
    val engineManifestUrl: String get() = props.getProperty("engineManifestUrl", "")
    val podcastIndexKey: String get() = props.getProperty("podcastIndexKey", "")
    val podcastIndexSecret: String get() = props.getProperty("podcastIndexSecret", "")

    val shippedLocales: List<String>
        get() = props.getProperty("shippedLocales", "en-US").split(',').filter { it.isNotBlank() }
}
